name: demoapp
description: demo_app


publish_to: 'none'

version: 4.1.1+4

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  moor_flutter: ^2.1.0
  darq: ^0.5.1
  auto_size_text: ^2.1.0
  path_provider: ^1.6.28
  flutter_speed_dial: ^1.2.5
  flutter_local_notifications: 3.0.0
  device_info: 1.0.0
  url_launcher: ^5.0.2
  flutter_secure_storage: ^3.3.1+1
  image_picker: ^0.6.7+22
  image_cropper: ^1.2.1
  built_collection: ^4.2.2
  built_value: ^7.0.6

  http: ^0.12.0+2

  logging: ">=0.11.4 <2.0.0"

  font_awesome_flutter: ^8.4.0

  webview_flutter: ^0.3.7+1

  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  provider: ^2.0.1

  shared_preferences: ^0.5.2+1

dev_dependencies:
  build_resolvers: ^1.3.11
  build_runner: ^1.9.0
  built_value_generator: ^7.0.6
  moor_generator: ^2.1.0

  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: '0.39.14'

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf